Updated way of adding items to collections
datalab-org/datalab pull request #828
Opened 2024-07-31 13:52 UTC by BenjaminCharmes

Closes #819 

Add functionality to /collections route to receive and add a list of items to a list of collections

2024-07-31 14:32 UTC, BenjaminCharmes commented
pre-commit.ci autofix

2024-09-06 12:55 UTC, ml-evs commented
pre-commit.ci run

2024-09-06 12:59 UTC, ml-evs commented
pre-commit.ci run

2024-09-06 13:04 UTC, ml-evs commented
pre-commit.ci autofix

2024-09-06 13:06 UTC, ml-evs reviewed
Looks good, could we just fix this bug where the buttons remain clickable after deleting a selected sample?

2024-09-06 13:10 UTC, ml-evs reviewed
Final comment: in a future PR it might be nice to also allow creation of a new collection based on the selection

2024-09-06 13:10 UTC, ml-evs commented on webapp/src/components/AddToCollectionModal.vue
> +            <label for="collection-select">(Optional) Insert into collection:</label>
```suggestion
            <label for="collection-select">Insert into collection:</label>
```

2024-09-06 13:11 UTC, ml-evs commented on pydatalab/pydatalab/routes/v0_1/collections.py
> +    if not refcodes:
Can we add a couple of Python tests for this functionality too? Ideally this could extend the item graph tests

2024-09-10 10:05 UTC, ml-evs commented
pre-commit.ci autofix

2024-09-10 14:00 UTC, ml-evs requested changes

2024-09-10 14:00 UTC, ml-evs commented on pydatalab/pydatalab/routes/v0_1/collections.py
> +        {"refcode": {"$in": refcodes}},
```suggestion
        {"refcode": {"$in": refcodes}, **get_default_permissions()},
```

2024-09-10 21:34 UTC, ml-evs approved these changes
Looks great, thanks @BenjaminCharmes!

2024-09-10 22:11 UTC, merged